version: '3'

services:
  backend:
    image: mayarmoahmed/server
    ports:
      - "5000:5000"
  frontend:
    image: mayarmoahmed/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
